#!/bin/bash
set -euo pipefail

# ============================================================
# Run SCNIC Network Analysis
# ============================================================
# Required input files in data/network_analysis/outputs/:
#   otu_table_ASV.biom
#   taxonomy_ASV.tsv
#   site1_otu.biom, site1_taxonomy.tsv
#   site2_otu.biom, site2_taxonomy.tsv
#   site3_otu.biom, site3_taxonomy.tsv
#   site4_otu.biom, site4_taxonomy.tsv
#
# Additional files generated by the previous R script but not used here:
#   metadata.tsv
#   site*_metadata.tsv
#   all_asv_domain.tsv
#   site*_asv_domain.tsv
#
# Activate QIIME2 before running this script:
#   conda activate qiime2-XXXX.X

# ============================================================
# Overall Network
# ============================================================
cd data/network_analysis

biom convert \
    -i outputs/otu_table_ASV.biom \
    -o outputs/otu_table_ASV_v210.biom \
    --table-type="OTU table" \
    --to-hdf5

qiime tools import \
    --input-path outputs/otu_table_ASV_v210.biom \
    --type 'FeatureTable[Frequency]' \
    --input-format BIOMV210Format \
    --output-path outputs/feature-table.qza

qiime tools import \
  --input-path outputs/taxonomy_ASV.tsv \
  --type 'FeatureData[Taxonomy]' \
  --output-path outputs/taxonomy.qza

qiime feature-table filter-features \
  --i-table outputs/feature-table.qza \
  --p-min-frequency 10 \
  --o-filtered-table outputs/filtered-table.qza

qiime feature-table filter-samples \
  --i-table outputs/filtered-table.qza \
  --p-min-frequency 1000 \
  --o-filtered-table outputs/filtered-samples-table.qza

qiime composition add-pseudocount \
  --i-table outputs/filtered-samples-table.qza \
  --o-composition-table outputs/table-with-pseudocount.qza

qiime tools export \
  --input-path outputs/table-with-pseudocount.qza \
  --output-path outputs/exported_data

qiime tools import \
  --type 'FeatureTable[Frequency]' \
  --input-path outputs/exported_data/feature-table.biom \
  --output-path outputs/table-frequency.qza \
  --input-format BIOMV210Format

qiime SCNIC calculate-correlations \
  --i-table outputs/table-frequency.qza \
  --p-method sparcc \
  --o-correlation-table outputs/correlations.qza

qiime SCNIC make-modules-on-correlations \
  --i-correlation-table outputs/correlations.qza \
  --i-feature-table outputs/table-frequency.qza \
  --p-min-r 0.3 \
  --o-collapsed-table outputs/collapsed-table.qza \
  --o-correlation-network outputs/correlation-network.qza \
  --o-module-membership outputs/module-membership.qza

qiime tools export \
  --input-path outputs/correlation-network.qza \
  --output-path outputs/exported-network

qiime tools export \
  --input-path outputs/correlations.qza \
  --output-path outputs/exported-corr

# ============================================================
# Site-specific Networks
# ============================================================
for site in site1 site2 site3 site4; do
  biom convert \
    -i outputs/${site}_otu.biom \
    -o outputs/${site}_otu_v210.biom \
    --table-type="OTU table" \
    --to-hdf5

  qiime tools import \
    --input-path outputs/${site}_otu_v210.biom \
    --type 'FeatureTable[Frequency]' \
    --input-format BIOMV210Format \
    --output-path outputs/${site}_feature-table.qza

  qiime tools import \
    --input-path outputs/${site}_taxonomy.tsv \
    --type 'FeatureData[Taxonomy]' \
    --output-path outputs/${site}_taxonomy.qza

  qiime feature-table filter-features \
    --i-table outputs/${site}_feature-table.qza \
    --p-min-frequency 10 \
    --o-filtered-table outputs/${site}_filt-table.qza

  qiime feature-table filter-samples \
    --i-table outputs/${site}_filt-table.qza \
    --p-min-frequency 1000 \
    --o-filtered-table outputs/${site}_filt-samples.qza

  qiime composition add-pseudocount \
    --i-table outputs/${site}_filt-samples.qza \
    --o-composition-table outputs/${site}_comp.qza

  qiime tools export \
    --input-path outputs/${site}_comp.qza \
    --output-path outputs/${site}_exported

  qiime tools import \
    --type 'FeatureTable[Frequency]' \
    --input-path outputs/${site}_exported/feature-table.biom \
    --output-path outputs/${site}_table-frequency.qza \
    --input-format BIOMV210Format

  qiime SCNIC calculate-correlations \
    --i-table outputs/${site}_table-frequency.qza \
    --p-method sparcc \
    --o-correlation-table outputs/${site}_correlations.qza

  qiime SCNIC make-modules-on-correlations \
    --i-correlation-table outputs/${site}_correlations.qza \
    --i-feature-table outputs/${site}_table-frequency.qza \
    --p-min-r 0.3 \
    --o-collapsed-table outputs/${site}_collapsed.qza \
    --o-correlation-network outputs/${site}_network.qza \
    --o-module-membership outputs/${site}_modules.qza

  qiime tools export \
    --input-path outputs/${site}_network.qza \
    --output-path outputs/${site}_net_export

  qiime tools export \
    --input-path outputs/${site}_correlations.qza \
    --output-path outputs/${site}_corr_export
done