# ============================================================
# Input
# ============================================================
# This script requires a domain-specific phyloseq object
# generated by scripts/Main/00_1_asv_filter_fun.R.
#
# Available input file:
#   outputs/ps_final_fun.rds

# ============================================================
# Load libraries
# ============================================================
library(tidyverse)
library(phyloseq)
library(car)
library(FSA)
library(rstatix)
library(ggpubr)

theme_set(theme_bw())

# ============================================================
# Load phyloseq object
# ============================================================
ps_final <- readRDS("outputs/ps_final_fun.rds")

# ============================================================
# Statistical Tests Per Substrate
# ============================================================
substrates <- c("leaf", "tile_l", "tile_d", "sediment_5", "sediment_20")

for (substrate in substrates) {
  cat("\n==== Substrate:", substrate, "====\n")
  
  ps_sub <- subset_samples(ps_final, Type == substrate)
  df_sub <- as.data.frame(as.matrix(sample_data(ps_sub)))
  
  # Convert and clean qPCR values
  df_sub$qpcr <- as.numeric(as.character(df_sub$qpcr))
  df_sub <- df_sub[!is.na(df_sub$qpcr), ]
  df_sub$log_qpcr <- log10(df_sub$qpcr)
  
  # Shapiro-Wilk test
  shapiro_test <- df_sub %>%
    group_by(Site) %>%
  summarise(
    n = sum(!is.na(log_qpcr)),
    p_value = ifelse(n >= 3, shapiro.test(log_qpcr)$p.value, NA_real_),
    .groups = "drop"
  )
  
  print("Shapiro-Wilk normality test:")
  print(shapiro_test)
  
  if (all(!is.na(shapiro_test$p_value)) && all(shapiro_test$p_value > 0.05)) {
    cat("→ ANOVA selected\n")
    result <- aov(log_qpcr ~ Site, data = df_sub)
    print(summary(result))
    print(TukeyHSD(result))
  } else {
    cat("→ Kruskal-Wallis + Dunn's test selected\n")
    print(kruskal.test(log_qpcr ~ Site, data = df_sub))
    print(
      df_sub %>% dunn_test(log_qpcr ~ Site, p.adjust.method = "bonferroni")
    )
  }
}

# ============================================================
# Visualization
# ============================================================
df <- as.data.frame(as.matrix(sample_data(ps_final)))
df$qpcr <- as.numeric(as.character(df$qpcr))
df <- df[!is.na(df$qpcr), ]
df$log_qpcr <- log10(df$qpcr)

df <- df %>%
  mutate(
    Site = factor(Site, levels = c("1", "2", "3", "4")),
    Type = factor(Type, levels = c("leaf", "sediment_20", "sediment_5", "tile_d", "tile_l"))
  )

stat.test <- df %>%
  group_by(Type) %>%
  dunn_test(log_qpcr ~ Site, p.adjust.method = "bonferroni") %>%
  add_xy_position(x = "Site", dodge = 0.8)

p <- ggplot(df, aes(x = Site, y = log_qpcr, fill = Site)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  facet_wrap(~ Type, nrow = 1, scales = "free_y") +
  stat_pvalue_manual(
    stat.test,
    label = "p.adj.signif",
    tip.length = 0.01,
    hide.ns = TRUE
  ) +
  labs(
    x = "Site",
    y = expression(log[10]~"(copy number)")
  ) +
  theme_minimal(base_family = "Helvetica") +
  theme(
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16, face = "bold"),
    strip.text = element_text(size = 18, face = "bold"),
    legend.title = element_blank(),
    legend.text = element_text(size = 13)
  )

p +
    labs(tag = "(B) Fungi") +
    theme(
        plot.tag = element_text(
            size = 22,
            face = "bold",
            family = "Helvetica"
        ),
        plot.tag.position = "topleft"
    )