# ============================================================
# Input
# ============================================================
# This script requires a domain-specific phyloseq object
# generated by scripts/Main/00_1_asv_filter_bac.R.
#
# Available input file:
#   outputs/ps_final_bac.rds

# ============================================================
# Load libraries
# ============================================================
library(phyloseq)
library(dplyr)
library(ggplot2)

# Set default ggplot theme
theme_set(theme_bw())

# ============================================================
# Load phyloseq object
# ============================================================
ps_final <- readRDS("outputs/ps_final_bac.rds")

# ============================================================
# Visualization (Phylum level)
# ============================================================
ps_f <- ps_final
tax <- tax_table(ps_f) %>% as.data.frame()
tax$Phylum <- ifelse(is.na(tax$Phylum) | tax$Phylum == "", "Unknown", tax$Phylum)
tax_table(ps_f) <- as.matrix(tax)

ps_bac_phylum <- tax_glom(ps_f, taxrank = "Phylum")
ps_bac_rel <- transform_sample_counts(ps_bac_phylum, function(x) x / sum(x))
df <- psmelt(ps_bac_rel)
df$Phylum <- ifelse(is.na(df$Phylum) | df$Phylum == "", "Unknown", df$Phylum)

top_phyla <- df %>%
  group_by(Phylum) %>%
  summarise(mean_abund = mean(Abundance, na.rm = TRUE)) %>%
  arrange(desc(mean_abund)) %>%
  slice_head(n = 8) %>%
  pull(Phylum)

top_phyla <- unique(c(top_phyla, "Unknown"))

df <- df %>%
  mutate(Phylum = ifelse(Phylum %in% top_phyla, Phylum, "Other"))

df_summary <- df %>%
  group_by(Description, Phylum) %>%
  summarise(mean_abund = mean(Abundance, na.rm = TRUE), .groups = "drop")

df_summary <- df_summary %>%
  group_by(Description) %>%
  mutate(mean_abund = mean_abund / sum(mean_abund)) %>%
  ungroup()
  
df_summary$Phylum <- factor(df_summary$Phylum,
                            levels = c("Unknown", top_phyla[!top_phyla %in% c("Unknown")], "Other"))

bac_colors <- c(
  "Proteobacteria" = "#8491B4FF",
  "Bacteroidota" = "#E69F00",
  "Actinobacteriota" = "#CC79A7",
  "Firmicutes" = "#009E73",
  "Planctomycetota" = "#56B4E9",
  "Cyanobacteria" = "#0072B2",
  "Verrucomicrobiota" = "#F39B7FFF",
  "Patescibacteria" = "#AD8BC9FF",
  "Unknown" = "#BFBFBF",
  "Other" = "grey80"
)

p <- ggplot(df_summary, aes(x = Description, y = mean_abund, fill = Phylum)) +
  geom_bar(stat = "identity", width = 0.8) +
  scale_fill_manual(values = bac_colors) +
  labs(x = "Sample", y = "Relative abundance", fill = "Phylum") +
  theme_bw(base_family = "Arial", base_size = 18) +
  theme(
    panel.border = element_rect(color = "black", linewidth = 0.6),
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 13),
    axis.text.y = element_text(size = 15),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    legend.key.size = unit(0.6, "cm")
  ) +
  theme(aspect.ratio = 0.8)

ggsave(
  filename = "Suppl_Fig7A.pdf",
  plot = p,
  device = cairo_pdf,
  width = 230,
  height = 180,
  units = "mm",
  bg = "white"
)

# ============================================================
# Visualization (Family level)
# ============================================================
ps_f <- ps_final
tax <- tax_table(ps_f) %>% as.data.frame()
tax$Phylum <- ifelse(is.na(tax$Phylum) | tax$Phylum == "", "Unknown", tax$Phylum)
tax_table(ps_f) <- as.matrix(tax)

ps_bac_family <- tax_glom(ps_f, taxrank = "Family")
ps_bac_rel <- transform_sample_counts(ps_bac_family, function(x) x / sum(x))
df <- psmelt(ps_bac_rel)
df$Family <- ifelse(is.na(df$Family) | df$Family == "", "Unknown", df$Family)

top_family <- df %>%
  filter(!Family %in% c("Other", "Unknown")) %>%  # ← ここで除外
  group_by(Family) %>%
  summarise(mean_abund = mean(Abundance, na.rm = TRUE), .groups = "drop") %>%
  arrange(desc(mean_abund)) %>%
  slice_head(n = 10) %>%
  pull(Family)

df <- df %>%
  mutate(Family = ifelse(Family %in% top_family, Family, "Other"))

df_summary <- df %>%
  group_by(Description, Family) %>%
  summarise(mean_abund = mean(Abundance, na.rm = TRUE), .groups = "drop") %>%
  group_by(Description) %>%
  mutate(mean_abund = mean_abund / sum(mean_abund)) %>%
  ungroup()

df_summary$Family <- factor(df_summary$Family, 
                            levels = c("Other", setdiff(unique(df_summary$Family), "Other")))

palette_pastel_bac <- c(
  "Sphingomonadaceae"      = "#DDAA66",
  "Comamonadaceae"         = "#6CBED5",
  "Spirosomaceae"          = "#66B2A3",
  "Rhizobiales_Incertae_Sedis" = "#5A6FAE",
  "Flavobacteriaceae"      = "#E59880",
  "Rhodobacteraceae"       = "#9B97B7",
  "Pirellulaceae"          = "#8EC5BE",
  "Phormidiaceae"          = "#CC7B7B",
  "Ilumatobacteraceae"     = "#9C8675",
  "Rubinisphaeraceae"      = "#B9A998",
  "Other"                  = "grey85"
)

p <- ggplot(df_summary, aes(x = Description, y = mean_abund, fill = Family)) +
  geom_bar(stat = "identity", width = 0.8) +
  scale_fill_manual(values = palette_pastel_bac, name = "Family") +
  labs(x = "Sample", y = "Relative abundance") +
  theme_bw(base_size = 18, base_family = "Arial") +
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(color = "black", linewidth = 0.6),
    legend.position = "right",
    legend.title = element_text(face = "bold", size = 13),
    legend.text = element_text(size = 11),
    axis.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 13),
    axis.text.y = element_text(size = 15)
  ) +
  theme(aspect.ratio = 0.8)

ggsave(
  filename = "Suppl_Fig8A.pdf",
  plot = p,
  device = cairo_pdf,
  width = 230,
  height = 180,
  units = "mm",
  bg = "white"
)